import Ionicons from '@expo/vector-icons/Ionicons';
import { type Href, useRouter } from 'expo-router';
import React, { useMemo, useRef, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { HomeGnb, HomeTask, HomeTaskList, TaskDetailBottomSheet, type Difficulty } from '../../components/home';
import { AssetIcon } from '../../components/ui';
import { Colors } from '../../constants/colors';

const INITIAL_TASKS: HomeTask[] = [
  { id: 'textbook', subject: '확률과통계', title: '교과서 63-100쪽 개념 정독', completed: false, difficulty: null },
  { id: 'language', subject: '언어와매체', title: '수능특강 언론예술 08~10장 정리', completed: false, difficulty: null },
  { id: 'suneung-4-7', subject: '확률과통계', title: '수능특강 4강-7강 문제풀이', completed: false, difficulty: null, strategyAvailable: true },
  { id: 'society', subject: '언어와매체', title: '수능특강 언론예술 11~13강 + 사회문화 08~13강', completed: false, difficulty: null },
  { id: 'french', subject: '프랑스어문화', title: '수능특강 7~9강 정리', completed: false, difficulty: null },
  { id: 'history', subject: '한국사', title: '교과서 178~210쪽 흐름 정리', completed: false, difficulty: null },
];

export default function HomeScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const scrollRef = useRef<ScrollView>(null);
  const [tasks, setTasks] = useState(INITIAL_TASKS);
  const [detailTaskId, setDetailTaskId] = useState<string | null>(null);
  const [message, setMessage] = useState('');
  const [stageAdvanced, setStageAdvanced] = useState(false);
  const selectedTask = useMemo(() => tasks.find(task => task.id === detailTaskId) ?? null, [detailTaskId, tasks]);
  const allTasksCompleted = tasks.every(task => task.completed);

  const toggleTask = (taskId: string) => setTasks(current => current.map(task => task.id === taskId ? { ...task, completed: !task.completed, difficulty: task.completed ? null : task.difficulty } : task));
  const selectDifficulty = (taskId: string, difficulty: Difficulty) => setTasks(current => current.map(task => task.id === taskId ? { ...task, difficulty } : task));
  const openStrategy = (task: HomeTask) => { if (task.id === 'suneung-4-7') setDetailTaskId(task.id); };

  return <SafeAreaView edges={['top', 'left', 'right']} style={styles.safeArea}>
    <View style={styles.viewport}>
      <ScrollView ref={scrollRef} contentContainerStyle={[styles.content, { paddingBottom: 94 + insets.bottom }]} showsVerticalScrollIndicator={false}>
        <View style={styles.topBar}><View style={styles.dateInfo}><View style={styles.calendarIcon}><Ionicons name="calendar-outline" size={18} color="#56585A" /></View><Text style={styles.dateText}>2026년 6월 23일 화요일</Text></View><Pressable accessibilityLabel="알림"><Ionicons name="notifications-outline" size={22} color="#56585A" /></Pressable></View>
        <View style={styles.dashboard}><View style={styles.examCard}><View style={styles.ddayBadge}><Text style={styles.ddayText}>D-14</Text></View><Text style={styles.examTitle}>기말고사</Text><Text style={styles.examBody}>7/2(목) 확률과통계 ·{`\n`}언어와매체 · 한국사</Text></View><View style={styles.stageCard}><Text style={styles.stageLabel}>현재 스테이지</Text><Text style={styles.stageBody}>Stage {stageAdvanced ? '3' : '2'}</Text><View style={styles.progressTrack}><View style={[styles.progressFill, stageAdvanced && styles.progressFillStageThree]} /></View><Text style={styles.progressLabel}>{stageAdvanced ? '100%' : '55%'}</Text></View></View>
        <View style={styles.tutorCard}><View style={styles.tutorTitleRow}><View style={styles.tutorIcon}><Ionicons name="sparkles" size={17} color="#FFFFFF" /></View><Text style={styles.tutorTitle}>루미 튜터</Text></View><Text style={styles.tutorBody}>사회문화 1회독 완료 대박이야! D-14부터가 진짜 승부인데 지금 페이스 완벽해. 오늘은 확통 수특 4-7강 집중해봐. 조합 · 이항정리 유형이 이번 시험 핵심이야.</Text></View>
        <View style={styles.section}><View style={styles.stageChip}><Text style={styles.stageChipText}>STAGE {stageAdvanced ? '3' : '2'}</Text></View><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{stageAdvanced ? '문제풀이 집중' : '심화 개념 정리'}</Text><Text style={styles.sectionPeriod}>{stageAdvanced ? 'D-13 ~ D-7' : 'D-21 ~ D-14'}</Text></View><View style={styles.stageProgress}><View style={styles.stageSegment}><View style={[styles.stageSegmentFill, { width: '100%' }]} /></View><View style={styles.stageSegment}><View style={[styles.stageSegmentFill, { width: stageAdvanced ? '100%' : '45%' }]} /></View><View style={styles.stageSegment}>{stageAdvanced && <View style={styles.stageSegmentFill} />}</View><View style={styles.stageSegment} /></View><View style={styles.stageLabels}><Text>S1</Text><Text>S2</Text><Text>S3</Text><Text>S4</Text></View>{stageAdvanced ? <View style={styles.blankTaskList}>{Array.from({ length: 6 }, (_, index) => <View key={index} style={styles.blankTaskRow}><View style={styles.blankCheckbox} /><View style={styles.blankText} /><Ionicons name="chevron-forward" size={20} color="#D3D5D7" /></View>)}</View> : <HomeTaskList tasks={tasks} onToggle={toggleTask} onSelectDifficulty={selectDifficulty} onOpenStrategy={openStrategy} />}</View>
        <Pressable disabled={!allTasksCompleted || stageAdvanced} onPress={() => setStageAdvanced(true)} style={[styles.nextStage, (!allTasksCompleted || stageAdvanced) && styles.nextStageInactive]}><View style={[styles.nextStageIcon, allTasksCompleted && !stageAdvanced && styles.nextStageIconActive]}><Ionicons name="flag-outline" size={17} color={allTasksCompleted && !stageAdvanced ? '#FFFFFF' : '#5299A4'} /></View><View style={styles.nextStageCopy}><Text style={[styles.nextStageTitle, (!allTasksCompleted || stageAdvanced) && styles.nextStageTextInactive]}>{stageAdvanced ? '현재 Stage 3을 학습 중이에요' : '다음 스테이지 보러 가기'}</Text><Text style={styles.nextStageBody}>{stageAdvanced ? '학습 내용이 준비 중이에요' : 'Stage 3 · 문제풀이 집중(D-13 ~ D-7)'}</Text></View><Ionicons name="chevron-forward" size={20} color={allTasksCompleted && !stageAdvanced ? '#56585A' : '#A1A3A5'} /></Pressable>
        <View style={styles.chatSection}><View style={styles.chatHeader}><View style={styles.chatTitleRow}><View style={styles.chatIcon}><Ionicons name="chatbubble-ellipses" size={15} color="#FFFFFF" /></View><Text style={styles.chatTitle}>루미 튜터</Text></View><Text style={styles.chatStatus}>오늘 아직 보고 안 함</Text></View><Text style={styles.chatPrompt}>자주 입력할수록 정확한 전략 리포트를 생성해요!</Text><View style={styles.chatBox}><TextInput value={message} onChangeText={setMessage} multiline maxLength={400} placeholder="오늘 공부하면서 어땠어? 막힌 거나 고민 있으면 말해줘!" placeholderTextColor="#A1A3A5" style={styles.chatInput} /><Pressable onPress={() => setMessage('')} style={styles.sendButton}><Text style={styles.sendText}>보내기</Text></Pressable></View><Text style={styles.wordCount}>{message.length}/400</Text></View>
      </ScrollView>
      <Pressable accessibilityLabel="맨 위로 이동" onPress={() => scrollRef.current?.scrollTo({ y: 0, animated: true })} style={[styles.topButton, { bottom: 68 + insets.bottom }]}><AssetIcon name="up" width={40} height={40} /></Pressable>
      <HomeGnb bottomInset={insets.bottom} onReportPress={() => router.replace('/report')} onMyPagePress={() => router.replace('/MyPage' as Href)} />
      <TaskDetailBottomSheet visible={!!selectedTask} difficulty={selectedTask?.difficulty ?? null} onClose={() => setDetailTaskId(null)} />
    </View>
  </SafeAreaView>;
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FFFFFF' }, viewport: { flex: 1, backgroundColor: '#FFFFFF' }, content: { gap: 20, paddingHorizontal: 20, paddingTop: 8 },
  topBar: { height: 36, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, dateInfo: { flexDirection: 'row', alignItems: 'center', gap: 8 }, calendarIcon: { width: 28, height: 28, borderWidth: 1, borderRadius: 8, borderColor: Colors['Line.Normal.Normal'], alignItems: 'center', justifyContent: 'center' }, dateText: { color: '#3B3D3F', fontFamily: 'Pretendard-Medium', fontSize: 14, lineHeight: 20 },
  dashboard: { flexDirection: 'row', gap: 6 }, examCard: { flex: 1, minHeight: 112, gap: 4, padding: 12, borderWidth: 1, borderRadius: 16, borderColor: Colors['Line.Normal.Strong'] }, ddayBadge: { alignSelf: 'flex-start', paddingHorizontal: 12, paddingVertical: 3, borderRadius: 8, backgroundColor: '#66BFCD' }, ddayText: { color: '#FFFFFF', fontFamily: 'Pretendard-SemiBold', fontSize: 12, lineHeight: 16 }, examTitle: { color: '#242628', fontFamily: 'Pretendard-SemiBold', fontSize: 16, lineHeight: 22 }, examBody: { color: '#707275', fontFamily: 'Pretendard-Regular', fontSize: 11, lineHeight: 16 },
  stageCard: { flex: 1, minHeight: 112, justifyContent: 'center', gap: 3, padding: 12, borderWidth: 1, borderRadius: 16, borderColor: Colors['Line.Normal.Normal'], backgroundColor: '#F6F8FA' }, stageLabel: { color: '#56585A', fontFamily: 'Pretendard-SemiBold', fontSize: 13, lineHeight: 18 }, stageBody: { color: '#8B8D8F', fontFamily: 'Pretendard-Regular', fontSize: 11, lineHeight: 16 }, progressTrack: { height: 6, overflow: 'hidden', borderRadius: 3, backgroundColor: '#ECEEF0' }, progressFill: { width: '55%', height: '100%', borderRadius: 3, backgroundColor: '#66BFCD' }, progressFillStageThree: { width: '100%' }, progressLabel: { alignSelf: 'flex-end', color: '#56585A', fontFamily: 'Pretendard-Medium', fontSize: 11 },
  tutorCard: { gap: 8, padding: 14, borderWidth: 1, borderRadius: 16, borderColor: Colors['Line.Normal.Strong'], backgroundColor: '#F6F8FA' }, tutorTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 }, tutorIcon: { width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#66BFCD' }, tutorTitle: { color: '#3B3D3F', fontFamily: 'Pretendard-SemiBold', fontSize: 15, lineHeight: 22 }, tutorBody: { color: '#56585A', fontFamily: 'Pretendard-Regular', fontSize: 13, lineHeight: 20 },
  section: { gap: 10 }, stageChip: { alignSelf: 'stretch', alignItems: 'center', paddingVertical: 4, borderWidth: 1, borderRadius: 8, borderColor: Colors['Line.Primary.Normal'], backgroundColor: Colors['Fill.Primary.Assistive'] }, stageChipText: { color: '#5299A4', fontFamily: 'Pretendard-SemiBold', fontSize: 11, lineHeight: 16 }, sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sectionTitle: { color: '#242628', fontFamily: 'Pretendard-SemiBold', fontSize: 17, lineHeight: 24 }, sectionPeriod: { color: '#8B8D8F', fontFamily: 'Pretendard-Regular', fontSize: 12, lineHeight: 18 }, stageProgress: { flexDirection: 'row', gap: 4 }, stageSegment: { flex: 1, height: 5, overflow: 'hidden', borderRadius: 3, backgroundColor: '#ECEEF0' }, stageSegmentFill: { height: '100%', borderRadius: 3, backgroundColor: '#3385FF' }, stageLabels: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 2 },
  blankTaskList: { overflow: 'hidden', borderWidth: 1, borderRadius: 16, borderColor: Colors['Line.Normal.Strong'], backgroundColor: '#FFFFFF' }, blankTaskRow: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: Colors['Line.Normal.Normal'] }, blankCheckbox: { width: 24, height: 24, borderWidth: 1, borderRadius: 8, borderColor: '#ECEEF0' }, blankText: { flex: 1, height: 12, borderRadius: 6, backgroundColor: '#F6F8FA' },
  nextStage: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: 14, backgroundColor: '#F6F8FA' }, nextStageInactive: { opacity: 0.58 }, nextStageIcon: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors['Fill.Primary.Assistive'] }, nextStageIconActive: { backgroundColor: '#5299A4' }, nextStageCopy: { flex: 1 }, nextStageTitle: { color: '#3B3D3F', fontFamily: 'Pretendard-SemiBold', fontSize: 14, lineHeight: 20 }, nextStageTextInactive: { color: '#707275' }, nextStageBody: { color: '#8B8D8F', fontFamily: 'Pretendard-Regular', fontSize: 11, lineHeight: 16 },
  chatSection: { gap: 6 }, chatHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, chatTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 }, chatIcon: { width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#5299A4' }, chatTitle: { color: '#3B3D3F', fontFamily: 'Pretendard-SemiBold', fontSize: 15, lineHeight: 22 }, chatStatus: { color: '#A1A3A5', fontFamily: 'Pretendard-Regular', fontSize: 10, lineHeight: 14 }, chatPrompt: { color: '#5299A4', fontFamily: 'Pretendard-Medium', fontSize: 12, lineHeight: 18 }, chatBox: { minHeight: 142, padding: 12, borderWidth: 1, borderRadius: 14, borderColor: Colors['Line.Normal.Strong'], backgroundColor: '#FFFFFF' }, chatInput: { minHeight: 82, padding: 0, color: '#3B3D3F', fontFamily: 'Pretendard-Regular', fontSize: 14, lineHeight: 20, textAlignVertical: 'top' }, sendButton: { alignSelf: 'flex-end', paddingHorizontal: 14, paddingVertical: 6, borderWidth: 1, borderRadius: 14, borderColor: Colors['Line.Primary.Normal'], backgroundColor: Colors['Fill.Primary.Assistive'] }, sendText: { color: '#5299A4', fontFamily: 'Pretendard-Medium', fontSize: 12, lineHeight: 18 }, wordCount: { alignSelf: 'flex-end', color: '#A1A3A5', fontFamily: 'Pretendard-Regular', fontSize: 11, lineHeight: 16 },
  topButton: { position: 'absolute', right: 16, width: 48, height: 48, borderWidth: 1, borderRadius: 16, borderColor: Colors['Line.Primary.Normal'], alignItems: 'center', justifyContent: 'center', backgroundColor: '#5299A4', elevation: 3 },
});
