import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/colors';

export type Tone = 'primary' | 'blue' | 'red' | 'orange' | 'green' | 'pink' | 'cyan' | 'teal' | 'assistive';

export const tone = {
  primary: Colors['Fill.Primary.Normal'],
  blue: '#3385FF',
  red: '#E35D6A',
  orange: '#D89221',
  green: '#58A51F',
  pink: '#F04588',
  cyan: '#00AFC7',
  teal: '#00AFC7',
  assistive: Colors['Text.Normal.Assistive'],
};

export const toneBg = {
  primary: Colors['Fill.Primary.Assistive'],
  blue: '#F2F7FF',
  red: '#FFF1F1',
  orange: '#FFF8EC',
  green: '#F4FFE8',
  pink: '#FFF1F7',
  cyan: '#EEFCFF',
  teal: '#ECFAF8',
  assistive: Colors['Fill.Normal.Assistive'],
};

export const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  divider: {
    height: 1,
    width: '100%',
    backgroundColor: Colors['Line.Normal.Normal'],
  },
  cursor: {
    width: 1,
    height: 16,
    backgroundColor: Colors['Text.Normal.Strong'],
  },
  list: {
    width: '100%',
    gap: 8,
  },
  listItem: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: Colors['Fill.Normal.Normal'],
    borderWidth: 1,
    borderColor: Colors['Line.Normal.Normal'],
  },
  selectedSurface: {
    borderColor: Colors['Line.Primary.Normal'],
    backgroundColor: Colors['Fill.Primary.Assistive'],
  },
  inactiveSurface: {
    opacity: 0.55,
  },
  card: {
    width: '100%',
    gap: 12,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors['Line.Normal.Normal'],
    backgroundColor: Colors['Fill.Normal.Normal'],
  },
  cardTitle: {
    color: Colors['Text.Normal.Strong'],
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 18,
    lineHeight: 28,
  },
  bodyStrong: {
    color: Colors['Text.Normal.Strong'],
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 16,
    lineHeight: 24,
  },
  body: {
    color: Colors['Text.Normal.Normal'],
    fontFamily: 'Pretendard-Medium',
    fontSize: 14,
    lineHeight: 22,
  },
  caption: {
    color: Colors['Text.Normal.Assistive'],
    fontFamily: 'Pretendard-Medium',
    fontSize: 12,
    lineHeight: 16,
  },
  primaryText: {
    color: Colors['Text.Primary.Strong'],
  },
  assistiveText: {
    color: Colors['Text.Normal.Assistive'],
  },
  inverseText: {
    color: Colors['Text.Normal.Inverse'],
  },
  loadingDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
    padding: 24,
  },
  loadingDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Colors['Fill.Normal.Inactive'],
  },
  loadingDotActive: {
    backgroundColor: Colors['Fill.Primary.Normal'],
  },
  datePicker: {
    flexDirection: 'row',
    gap: 8,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors['Line.Normal.Normal'],
    backgroundColor: Colors['Fill.Normal.Normal'],
  },
  dateItem: {
    width: 36,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 18,
  },
  dateSelected: {
    backgroundColor: Colors['Fill.Primary.Normal'],
  },
  dateEclipse: {
    color: Colors['Text.Normal.Assistive'],
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 18,
    lineHeight: 44,
  },
  faqItem: {
    width: '100%',
    minHeight: 64,
    gap: 8,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors['Line.Normal.Normal'],
    backgroundColor: Colors['Fill.Normal.Normal'],
  },
  gnbButton: {
    width: 48,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 2,
  },
  gnbLabel: {
    color: Colors['Text.Normal.Assistive'],
    fontFamily: 'Pretendard-Medium',
    fontSize: 10,
    lineHeight: 14,
  },
  progressIndicator: {
    width: 33,
    height: 33,
    borderRadius: 16.5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors['Fill.Primary.Assistive'],
  },
  progressIndicatorText: {
    color: Colors['Text.Primary.Strong'],
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 11,
  },
  progressTrack: {
    width: '100%',
    overflow: 'hidden',
    backgroundColor: Colors['Fill.Normal.Assistive'],
  },
  progressFill: {
    height: '100%',
    backgroundColor: Colors['Fill.Primary.Normal'],
  },
  textIconButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  characterBubble: {
    alignSelf: 'flex-start',
    maxWidth: 305,
    minHeight: 50,
    justifyContent: 'center',
    paddingHorizontal: 16,
    borderRadius: 18,
    backgroundColor: Colors['Fill.Primary.Assistive'],
  },
  policyAgree: {
    minHeight: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  chip: {
    minHeight: 28,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: Colors['Fill.Primary.Assistive'],
  },
  chipSecondary: {
    backgroundColor: Colors['Fill.Normal.Assistive'],
  },
  chipText: {
    color: Colors['Text.Primary.Strong'],
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 13,
    lineHeight: 18,
  },
  photo: {
    borderRadius: 16,
  },
  photoFallback: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors['Fill.Normal.Assistive'],
  },
  studyTypeScore: {
    width: 61,
    height: 63,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
    backgroundColor: Colors['Fill.Normal.Normal'],
  },
  scoreText: {
    color: Colors['Text.Normal.Strong'],
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 22,
    lineHeight: 28,
  },
  studyTypeGraph: {
    width: '100%',
    gap: 8,
  },
  graphTrack: {
    height: 12,
    borderRadius: 6,
    overflow: 'hidden',
    backgroundColor: Colors['Fill.Normal.Assistive'],
  },
  graphFill: {
    height: '100%',
    borderRadius: 6,
  },
  goodCard: {
    backgroundColor: '#F4FFE8',
  },
  badCard: {
    backgroundColor: '#FFF1F1',
  },
  difficultyLevel: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors['Fill.Normal.Assistive'],
  },
  difficultySelected: {
    backgroundColor: Colors['Fill.Primary.Normal'],
  },
  difficultyScore: {
    width: 59,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
    backgroundColor: Colors['Fill.Primary.Assistive'],
  },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors['Fill.Primary.Normal'],
  },
  fab: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 5,
  },
  homeChecklistItem: {
    width: '100%',
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors['Line.Normal.Normal'],
    backgroundColor: Colors['Fill.Normal.Normal'],
  },
  reportBoxItem: {
    width: '100%',
    minHeight: 118,
    gap: 8,
    padding: 16,
    borderRadius: 16,
  },
  reportProgressItem: {
    width: '100%',
    gap: 8,
  },
  numberBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  numberBadgeText: {
    color: '#FFFFFF',
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 14,
  },
  reportInfoCard: {
    width: 164.5,
    minHeight: 104,
    gap: 8,
    padding: 16,
    borderRadius: 16,
  },
});
