import { StyleSheet } from 'react-native';
import { Colors } from '../../../constants/colors';

export const subjectDetailStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FFFFFF' },
  header: {
    height: 88,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
  },
  backArrow: {
    fontSize: 28,
    color: Colors['Text.Normal.Strong'],
  },
  subjectBadge: {
    minWidth: 66,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5D5DF',
    backgroundColor: '#FFF7FB',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  subjectBadgeText: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 16,
    color: '#F04588',
  },
  subjectBadgeMath: {
    borderColor: '#D6E8C8',
    backgroundColor: '#FAFFF5',
  },
  subjectBadgeTextMath: {
    color: '#48AD00',
  },
  subjectBadgeEnglish: {
    borderColor: '#D5E2FF',
    backgroundColor: '#F5F8FF',
  },
  subjectBadgeTextEnglish: {
    color: '#3385FF',
  },
  subjectBadgeSocial: {
    borderColor: '#F0D9B7',
    backgroundColor: '#FFF8EF',
  },
  subjectBadgeTextSocial: {
    color: '#F68D00',
  },
  subjectBadgeScience: {
    borderColor: '#BCEAF2',
    backgroundColor: '#F0FCFE',
  },
  subjectBadgeTextScience: {
    color: '#00BDDE',
  },
  headerSpacer: { width: 40 },
  tabBar: {
    height: 58,
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: Colors['Line.Normal.Normal'],
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabItemActive: {
    borderBottomColor: Colors['Fill.Primary.Normal'],
  },
  tabText: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 16,
    color: Colors['Text.Normal.Assistive'],
  },
  tabTextActive: {
    color: '#4C8790',
  },
  scroll: { flex: 1 },
  content: {
    paddingHorizontal: 20,
    paddingTop: 34,
    paddingBottom: 120,
    gap: 30,
  },
  field: {
    gap: 12,
  },
  label: {
    fontFamily: 'Pretendard-Medium',
    fontSize: 16,
    color: Colors['Text.Normal.Normal'],
  },
  input: {
    height: 64,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors['Line.Normal.Strong'],
    paddingHorizontal: 18,
    fontFamily: 'Pretendard-Medium',
    fontSize: 16,
    color: Colors['Text.Normal.Strong'],
  },
  sliderValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  sliderTouchArea: {
    flex: 1,
    height: 44,
    justifyContent: 'center',
  },
  sliderTrack: {
    width: '100%',
    height: 7,
    borderRadius: 999,
    backgroundColor: Colors['Line.Normal.Normal'],
  },
  sliderFill: {
    height: 7,
    borderRadius: 999,
    backgroundColor: Colors['Fill.Primary.Normal'],
  },
  sliderThumb: {
    position: 'absolute',
    top: -10,
    width: 30,
    height: 30,
    marginLeft: -15,
    borderRadius: 15,
    borderWidth: 3,
    borderColor: Colors['Line.Normal.Normal'],
    backgroundColor: '#6E9CA4',
  },
  sliderValue: {
    width: 46,
    textAlign: 'right',
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 16,
    color: '#5F939B',
  },
  segmented: {
    height: 64,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors['Line.Normal.Strong'],
    padding: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  segmentItem: {
    flex: 1,
    height: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentItemSelected: {
    borderWidth: 1,
    borderColor: Colors['Line.Primary.Normal'],
    backgroundColor: Colors['Fill.Primary.Assistive'],
  },
  segmentText: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 18,
    color: Colors['Text.Normal.Assistive'],
  },
  segmentTextSelected: {
    color: Colors['Text.Normal.Normal'],
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  chip: {
    minHeight: 46,
    paddingHorizontal: 18,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors['Line.Normal.Strong'],
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  chipSelected: {
    borderColor: Colors['Line.Primary.Normal'],
    backgroundColor: Colors['Fill.Primary.Assistive'],
  },
  chipText: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 16,
    color: Colors['Text.Normal.Assistive'],
  },
  chipTextSelected: {
    color: Colors['Text.Normal.Normal'],
  },
  noticeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 10,
  },
  noticeIcon: {
    fontSize: 28,
  },
  noticeText: {
    flex: 1,
    fontFamily: 'Pretendard-Bold',
    fontSize: 16,
    color: Colors['Text.Normal.Strong'],
  },
  helperText: {
    fontFamily: 'Pretendard-Regular',
    fontSize: 13,
    color: Colors['Text.Normal.Assistive'],
  },
  uploadArea: {
    gap: 10,
  },
  uploadList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  uploadPreview: {
    width: 82,
    height: 56,
    borderRadius: 6,
    backgroundColor: '#EEF7F9',
    borderWidth: 1,
    borderColor: '#D8EEF2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadPreviewText: {
    fontFamily: 'Pretendard-Medium',
    fontSize: 12,
    color: Colors['Text.Normal.Assistive'],
  },
  uploadFile: {
    maxWidth: '100%',
    minHeight: 40,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: Colors['Line.Normal.Normal'],
    paddingLeft: 16,
    paddingRight: 36,
    justifyContent: 'center',
  },
  uploadFileText: {
    fontFamily: 'Pretendard-Regular',
    fontSize: 13,
    color: Colors['Text.Normal.Normal'],
  },
  uploadRemove: {
    position: 'absolute',
    right: -6,
    top: -6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors['Line.Normal.Normal'],
  },
  uploadRemoveText: {
    fontFamily: 'Pretendard-Bold',
    fontSize: 16,
    lineHeight: 18,
    color: Colors['Text.Normal.Normal'],
  },
  uploadButton: {
    height: 64,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors['Line.Normal.Strong'],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  uploadIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: Colors['Text.Normal.Normal'],
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: 22,
    fontFamily: 'Pretendard-Bold',
    fontSize: 15,
  },
  uploadText: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 18,
    color: Colors['Text.Normal.Normal'],
  },
  scheduleNoticeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  scheduleNoticeIcon: {
    fontSize: 28,
  },
  scheduleNoticeCopy: {
    flex: 1,
    gap: 4,
  },
  scheduleNoticeTitle: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 16,
    lineHeight: 24,
    color: Colors['Text.Normal.Strong'],
    letterSpacing: -0.3,
  },
  scheduleNoticeText: {
    fontFamily: 'Pretendard-Medium',
    fontSize: 14,
    lineHeight: 20,
    color: Colors['Text.Normal.Normal'],
    letterSpacing: -0.2,
  },
  scheduleSubjectRow: {
    flexDirection: 'row',
    gap: 6,
    paddingRight: 20,
  },
  scheduleSubjectChip: {
    minHeight: 40,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors['Line.Normal.Strong'],
    backgroundColor: Colors['Fill.Normal.Normal'],
    justifyContent: 'center',
    alignItems: 'center',
  },
  scheduleSubjectChipText: {
    fontFamily: 'Pretendard-Medium',
    fontSize: 16,
    lineHeight: 24,
    color: Colors['Text.Normal.Assistive'],
    letterSpacing: -0.2,
  },
  scheduleSubjectChipSelected: {
    borderColor: Colors['Line.Primary.Normal'],
    backgroundColor: Colors['Fill.Primary.Assistive'],
  },
  scheduleSubjectChipTextSelected: {
    color: Colors['Text.Normal.Normal'],
  },
  timetableCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors['Line.Normal.Strong'],
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 18,
    gap: 4,
  },
  timetableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  timeColumnSpacer: {
    width: 34,
    marginRight: 8,
  },
  timetableDay: {
    flex: 1,
    textAlign: 'center',
    fontFamily: 'Pretendard-Regular',
    fontSize: 14,
    lineHeight: 22,
    color: Colors['Text.Normal.Strong'],
    letterSpacing: -0.28,
  },
  timetableBody: {
    gap: 2,
  },
  timetableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  timetableTime: {
    width: 34,
    textAlign: 'right',
    fontFamily: 'Pretendard-Regular',
    fontSize: 12,
    lineHeight: 16,
    color: Colors['Text.Normal.Strong'],
    letterSpacing: -0.2,
  },
  timetableCellRow: {
    flex: 1,
    flexDirection: 'row',
    gap: 2,
  },
  timetableCell: {
    flex: 1,
  },
  scheduleHelperText: {
    fontFamily: 'Pretendard-Regular',
    fontSize: 13,
    lineHeight: 18,
    color: Colors['Text.Normal.Assistive'],
  },
  reconnectScreen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  reconnectBody: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 60,
  },
  reconnectMascot: {
    width: 112,
    height: 94,
    borderRadius: 30,
    backgroundColor: '#C9F6FA',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 28,
  },
  reconnectEyeRow: {
    flexDirection: 'row',
    gap: 12,
  },
  reconnectEye: {
    width: 18,
    height: 28,
    borderRadius: 10,
    backgroundColor: '#111111',
  },
  reconnectSmile: {
    width: 34,
    height: 20,
    borderBottomWidth: 3,
    borderColor: '#111111',
    borderRadius: 20,
  },
  reconnectTitle: {
    fontFamily: 'Pretendard-Bold',
    fontSize: 28,
    color: Colors['Text.Normal.Strong'],
    marginBottom: 18,
  },
  reconnectText: {
    fontFamily: 'Pretendard-Medium',
    fontSize: 16,
    color: Colors['Text.Normal.Strong'],
    marginBottom: 28,
  },
  reconnectSpinner: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 3,
    borderColor: '#D8EEF2',
    borderTopColor: Colors['Fill.Primary.Normal'],
  },
  buttonRow: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    gap: 14,
  },
  prevButton: {
    flex: 1,
    backgroundColor: Colors['Fill.Normal.Assistive'],
  },
  nextButton: {
    flex: 2,
  },
});
